search + pagination all working + restyle administration
fabien-design/MathIndex pull request #41
Opened 2024-03-27 15:53 UTC by TWhiteShadow

PR  infos           |                                                                                                                                                                                                       |
|------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Related issue  | Close #37                                                                                                                                                                                       |
| Kind of PR | <ul><li>[X] New feature</li><li>[ ] Bug fix</li><li>[X] Improvement</li></ul>                                                                                                                         |
| Impacts | <ul><li>[X] Back</li><li>[X] Front</li><li>[X] Infra</li><li>[ ] Translations</li><li>[ ] Bundles</li></ul>                                                                                           |

2024-03-27 17:07 UTC, fabien-design requested changes

2024-03-27 17:07 UTC, fabien-design commented on assets/styles/app.scss
> +        // }
tu en as besoin ? sinon tu peux enlever le commentaire

2024-03-28 07:52 UTC, TWhiteShadow commented on src/Entity/User.php
> +        $roles[] = 'ROLE_STUDENT';
ROLE_STUDENT devient la norme, ensuite une hiérarchie sépare les autres, avec ROLE_TEACHER et ROLE_ADMIN

2024-03-28 08:48 UTC, fabien-design approved these changes

2024-03-28 08:53 UTC, Magiks0 approved these changes

2024-03-28 08:53 UTC, Magiks0 commented on config/packages/knp_paginator.yaml
> +        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template
```suggestion
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template 
        
```

2024-03-28 08:53 UTC, Magiks0 commented on src/Controller/Administration/SearchController.php
> +
```suggestion
```

2024-03-28 08:53 UTC, Magiks0 commented on src/Form/ExerciseType.php
> +
```suggestion
```

2024-03-28 12:36 UTC, Magiks0 approved these changes

2024-03-28 13:07 UTC, Magiks0 approved these changes

2024-03-28 13:08 UTC, merged